/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, JoinColumn, Entity, OneToOne, ManyToOne, OneToMany, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';

import { File } from '../../file/models/File';
import { BetsGroup } from '../../bets-group/models/BetsGroup';
import { Round } from '../../round/models/Round';
import { HoleInOne } from '../../hole-in-one/models/HoleInOne';
import { HoleInOnePaymentObligation } from '../../hole-in-one-payment-obligation/models/HoleInOnePaymentObligation';
import { UserRole } from '../enums/UserRole';
import * as auth from '../../authorization/auth-checkers';
import { UserCreateInput } from '../inputs/UserCreateInput';
import { UserEditInput } from '../inputs/UserEditInput';
import { UserNestedInput } from '../inputs/UserNestedInput';
import { IRequestContext } from '../../shared/IRequestContext';
import { IAuthorizable } from '../../authorization/IAuthorizable';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { UserAuth } from '../auth/UserAuth';
import { getInputOperationType } from '../../shared/get-input-operation-type';
import { noChange } from '../../shared/no-change';
import { asPromise } from '../../shared/as-promise';

import { updateAvatarRelation,updateDumbHatPictureRelation } from './update-operations/user-update-operations';

// <keep-imports>
import { hashPassword, verifyPassword } from '../../authentication/crypto';
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class User implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  id: EntityId;

  public authorizationChecker = new UserAuth(this);

  @Field(() => String, {"nullable":true})
  @Column({"nullable":true,"type":"varchar",
    // <custom-column-args>
    // </custom-column-args>
  })
  public email?: string | null;

  
  @Column({"nullable":true,"type":"varchar",
    // <custom-column-args>
    // </custom-column-args>
  })
  public passwordHash?: string | null;

  @Field(() => String, )
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public firstName: string;

  @Field(() => String, )
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public lastName: string;

  
  @Column({"enum":UserRole,
    // <custom-column-args>
    // </custom-column-args>
  })
  public role: UserRole;

  @Field(() => String, {"nullable":true})
  @Column({"nullable":true,"type":"varchar",
    // <custom-column-args>
    // </custom-column-args>
  })
  public location?: string | null;

  @Field(() => String, {"nullable":true})
  @Column({"nullable":true,"type":"varchar",
    // <custom-column-args>
    // </custom-column-args>
  })
  public description?: string | null;

  @Field(() => Number, )
  @Column({"type":"integer",
    // <custom-column-args>
    // </custom-column-args>
  })
  public handicap: number;

  @Field(() => String, {"nullable":true})
  @Column({"nullable":true,"type":"varchar",
    // <custom-column-args>
    // </custom-column-args>
  })
  public phone?: string | null;

  @OneToMany(() => BetsGroup, (betsGroup) => betsGroup.user)
  @Field(() => [BetsGroup])
  public betsGroups: Promise<Array<BetsGroup>>;

  @OneToMany(() => Round, (round) => round.user)
  @Field(() => [Round])
  public rounds: Promise<Array<Round>>;

  @OneToMany(() => HoleInOne, (holeInOne) => holeInOne.winner)
  @Field(() => [HoleInOne])
  public holesInOne: Promise<Array<HoleInOne>>;

  @OneToMany(() => HoleInOnePaymentObligation, (holeInOnePaymentObligation) => holeInOnePaymentObligation.userWithPaymentObligation)
  @Field(() => [HoleInOnePaymentObligation])
  public paymentObligations: Promise<Array<HoleInOnePaymentObligation>>;

  @OneToOne(() => File, (file) => file.user)
  @Field(() => File , {"nullable":true})
  public avatar: Promise<File | undefined | null>;
  @OneToOne(() => File, (file) => file.dumbHatUser)
  @Field(() => File , {"nullable":true})
  public dumbHatPicture: Promise<File | undefined | null>;

  @CreateDateColumn()
  @Field()
  createdAt: Date;

  @UpdateDateColumn()
  @Field()
  updatedAt: Date;

  public async update(input: UserCreateInput | UserEditInput | UserNestedInput, context: IRequestContext) {
    const { avatar, dumbHatPicture, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

  await updateAvatarRelation(this, avatar, context);
  await updateDumbHatPictureRelation(this, dumbHatPicture, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    if (this.handicap === undefined) {
      this.handicap = 0;
    }
    if (this.role === undefined) {
      this.role = UserRole.USER;
    }
    if (input.password) {
      this.passwordHash = await hashPassword(input.password);
    } else if (!this.passwordHash) {
      throw new Error('Missing password in input');
    }
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  @Field(() => Number, )
  @Column({"type":"integer",
    default: 0,
  })
  public money: number;

  public async passwordMatches(password: string) {
    return verifyPassword(password, this.passwordHash);
  }
  // </keep-methods>
}
