/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Arg, Args, Mutation, Query, Info, ID, Ctx, Resolver, Root, FieldResolver, Int } from 'type-graphql';
import cleanDeep from 'clean-deep';

import { HoleInOne } from '../models/HoleInOne';
import { HoleInOneCreateInput } from '../inputs/HoleInOneCreateInput';
import { HoleInOneEditInput } from '../inputs/HoleInOneEditInput';
import { HoleInOneSearchInput } from '../inputs/HoleInOneSearchInput';
import { HoleInOneSearchOrderInput } from '../inputs/HoleInOneSearchOrderInput';
import { getFindOptions } from '../../shared/get-find-options';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { IRequestContext } from '../../shared/IRequestContext';
import * as auth from '../../authorization/auth-checkers';
import { PaginatedResponse } from '../../shared/PaginationResponse';
import { resolveGetters } from '../../shared/resolve-getters';

// <keep-imports>
// </keep-imports>

const PaginatedHoleInOneResponse = PaginatedResponse(HoleInOne);

@Resolver(HoleInOne)
export class HoleInOneCrudResolver {
  @Query(() => HoleInOne)
  async holeInOne(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.findOneOrFail(HoleInOne, id, getFindOptions(HoleInOne, info));
  }

  @Query(() => PaginatedHoleInOneResponse)
  public async searchHoleInOnes(
    @Arg('search', () => HoleInOneSearchInput, { nullable: true }) search: HoleInOneSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip = 0,
    @Arg('take', () => Int, { nullable: true }) take = 25,
    @Arg('order', () => [HoleInOneSearchOrderInput], { nullable: true }) order: Array<HoleInOneSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(HoleInOne, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = await ctx.em.findAndCount(HoleInOne, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    }));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [HoleInOne])
  async holeInOnes(@Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.find(HoleInOne, getFindOptions(HoleInOne, info));
  }

  @Mutation(() => HoleInOne)
  async createHoleInOne(@Arg('input') input: HoleInOneCreateInput, @Ctx() ctx: IRequestContext): Promise<HoleInOne> {
    const model = new HoleInOne();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => HoleInOne)
  async updateHoleInOne(@Arg('input') input: HoleInOneEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(HoleInOne, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  async deleteHoleInOnes(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(HoleInOne, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
