/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, JoinColumn, Entity, OneToOne, ManyToOne, OneToMany, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';

import { Round } from '../../round/models/Round';
import { Year } from '../../year/models/Year';

import * as auth from '../../authorization/auth-checkers';
import { WeekCreateInput } from '../inputs/WeekCreateInput';
import { WeekEditInput } from '../inputs/WeekEditInput';
import { WeekNestedInput } from '../inputs/WeekNestedInput';
import { IRequestContext } from '../../shared/IRequestContext';
import { IAuthorizable } from '../../authorization/IAuthorizable';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { WeekAuth } from '../auth/WeekAuth';
import { getInputOperationType } from '../../shared/get-input-operation-type';
import { noChange } from '../../shared/no-change';
import { asPromise } from '../../shared/as-promise';

import {  } from './update-operations/week-update-operations';

// <keep-imports>
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class Week implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  id: EntityId;

  public authorizationChecker = new WeekAuth(this);

  @Field(() => Number, )
  @Column({"type":"integer",
    // <custom-column-args>
    // </custom-column-args>
  })
  public weekNumber: number;

  @Field(() => Boolean, )
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public isActive: boolean;

  @ManyToOne(() => Year, (year) => year.weeks , {"nullable":false,"onDelete":"CASCADE"})
  @Field(() => Year , {"nullable":false})
  public year: Promise<Year>;

  @OneToMany(() => Round, (round) => round.week)
  @Field(() => [Round])
  public rounds: Promise<Array<Round>>;

  @CreateDateColumn()
  @Field()
  createdAt: Date;

  @UpdateDateColumn()
  @Field()
  updatedAt: Date;

  public async update(input: WeekCreateInput | WeekEditInput | WeekNestedInput, context: IRequestContext) {
    const data = input
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    if (getInputOperationType(this, input) === 'create') {
      this.year = asPromise(await this.year || await context.activeYear)
    }

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
