/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Arg, Args, Mutation, Query, Info, ID, Ctx, Resolver, Root, FieldResolver, Int } from 'type-graphql';
import cleanDeep from 'clean-deep';

import { Week } from '../models/Week';
import { WeekCreateInput } from '../inputs/WeekCreateInput';
import { WeekEditInput } from '../inputs/WeekEditInput';
import { WeekSearchInput } from '../inputs/WeekSearchInput';
import { WeekSearchOrderInput } from '../inputs/WeekSearchOrderInput';
import { getFindOptions } from '../../shared/get-find-options';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { IRequestContext } from '../../shared/IRequestContext';
import * as auth from '../../authorization/auth-checkers';
import { PaginatedResponse } from '../../shared/PaginationResponse';
import { resolveGetters } from '../../shared/resolve-getters';

// <keep-imports>
// </keep-imports>

const PaginatedWeekResponse = PaginatedResponse(Week);

@Resolver(Week)
export class WeekCrudResolver {
  @Query(() => Week)
  async week(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.findOneOrFail(Week, id, getFindOptions(Week, info));
  }

  @Query(() => PaginatedWeekResponse)
  public async searchWeeks(
    @Arg('search', () => WeekSearchInput, { nullable: true }) search: WeekSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip = 0,
    @Arg('take', () => Int, { nullable: true }) take = 25,
    @Arg('order', () => [WeekSearchOrderInput], { nullable: true }) order: Array<WeekSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(Week, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = await ctx.em.findAndCount(Week, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    }));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [Week])
  async weeks(@Info() info, @Ctx() ctx: IRequestContext) {
    console.log('week')
    const weeks = await ctx.em.find(Week, getFindOptions(Week, info));
    const today = new Date();
    console.log(today.getDay(),'----------')
    if (today.getDay() == 7) { // 6
      return weeks;
    }
    return weeks.filter(week => !week.isActive);
  }

  @Mutation(() => Week)
  async createWeek(@Arg('input') input: WeekCreateInput, @Ctx() ctx: IRequestContext): Promise<Week> {
    const model = new Week();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Week)
  async updateWeek(@Arg('input') input: WeekEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(Week, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  async deleteWeeks(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(Week, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
