/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';

import { UserNestedInput } from '../../user/inputs/UserNestedInput'

// <keep-imports>
// </keep-imports>

@InputType()
export class BetsGroupCreateInput {
  @Field(() => String, )
  public name: string;

  @Field(() => UserNestedInput, )
  public user: UserNestedInput;

  // <keep-methods>
  // </keep-methods>
}
