/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, JoinColumn, Entity, OneToOne, ManyToOne, OneToMany, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';

import { BetsGroup } from '../../bets-group/models/BetsGroup';

import * as auth from '../../authorization/auth-checkers';
import { BetCreateInput } from '../inputs/BetCreateInput';
import { BetEditInput } from '../inputs/BetEditInput';
import { BetNestedInput } from '../inputs/BetNestedInput';
import { IRequestContext } from '../../shared/IRequestContext';
import { IAuthorizable } from '../../authorization/IAuthorizable';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { BetAuth } from '../auth/BetAuth';
import { getInputOperationType } from '../../shared/get-input-operation-type';
import { noChange } from '../../shared/no-change';
import { asPromise } from '../../shared/as-promise';

import { updateBetsGroupRelation } from './update-operations/bet-update-operations';

// <keep-imports>
// </keep-imports>

// <keep-decorators>
// </keep-decorators>
@Entity()
@ObjectType()
export class Bet implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  id: EntityId;

  public authorizationChecker = new BetAuth(this);

  @Field(() => Date, )
  @Column({
    // <custom-column-args>
    // </custom-column-args>
  })
  public date: Date;

  @Field(() => Number, )
  @Column({"type":"integer",
    // <custom-column-args>
    // </custom-column-args>
  })
  public amount: number;

  @Field(() => String, )
  @Column({"type":"varchar",
    // <custom-column-args>
    // </custom-column-args>
  })
  public course: string;

  @Field(() => Number, {"nullable":true})
  @Column({"nullable":true,"type":"integer",
    // <custom-column-args>
    // </custom-column-args>
  })
  public currentAdvantage?: number | null;

  @Field(() => Number, {"nullable":true})
  @Column({"nullable":true,"type":"integer",
    // <custom-column-args>
    // </custom-column-args>
  })
  public nextAdvantage?: number | null;

  @ManyToOne(() => BetsGroup, (betsGroup) => betsGroup.bets , {"nullable":false,"onDelete":"CASCADE"})
  @Field(() => BetsGroup , {"nullable":false})
  public betsGroup: Promise<BetsGroup>;

  @CreateDateColumn()
  @Field()
  createdAt: Date;

  @UpdateDateColumn()
  @Field()
  updatedAt: Date;

  public async update(input: BetCreateInput | BetEditInput | BetNestedInput, context: IRequestContext) {
    const { betsGroup, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    await updateBetsGroupRelation(this, betsGroup, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
