/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';

import { BetsGroupNestedInput } from '../../bets-group/inputs/BetsGroupNestedInput'

// <keep-imports>
// </keep-imports>

@InputType()
export class BetEditInput {
  @Field(() => EntityIdScalar, )
  public id: EntityId;

  @Field(() => Date, {"nullable":true})
  public date?: Date | null;

  @Field(() => Number, {"nullable":true})
  public amount?: number | null;

  @Field(() => String, {"nullable":true})
  public course?: string | null;

  @Field(() => Number, {"nullable":true})
  public currentAdvantage?: number | null;

  @Field(() => Number, {"nullable":true})
  public nextAdvantage?: number | null;

  @Field(() => BetsGroupNestedInput, {"nullable":true})
  public betsGroup?: BetsGroupNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
