/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';

import { SortOrderEnum } from '../../shared/SortOrderEnum'

// <keep-imports>
// </keep-imports>

@InputType()
export class BetSearchOrderInput {
  @Field(() => SortOrderEnum, {"nullable":true})
  public id?: SortOrderEnum;

  @Field(() => SortOrderEnum, {"nullable":true})
  public date?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public amount?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public course?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public currentAdvantage?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public nextAdvantage?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public betsGroup?: SortOrderEnum | null;

  // <keep-methods>
  // </keep-methods>
}
