/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Arg, Args, Mutation, Query, Info, ID, Ctx, Resolver, Root, FieldResolver, Int } from 'type-graphql';
import cleanDeep from 'clean-deep';

import { Club } from '../models/Club';
import { ClubCreateInput } from '../inputs/ClubCreateInput';
import { ClubEditInput } from '../inputs/ClubEditInput';
import { ClubSearchInput } from '../inputs/ClubSearchInput';
import { ClubSearchOrderInput } from '../inputs/ClubSearchOrderInput';
import { getFindOptions } from '../../shared/get-find-options';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { IRequestContext } from '../../shared/IRequestContext';
import * as auth from '../../authorization/auth-checkers';
import { PaginatedResponse } from '../../shared/PaginationResponse';
import { resolveGetters } from '../../shared/resolve-getters';

// <keep-imports>
// </keep-imports>

const PaginatedClubResponse = PaginatedResponse(Club);

@Resolver(Club)
export class ClubCrudResolver {
  @Query(() => Club)
  async club(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.findOneOrFail(Club, id, getFindOptions(Club, info));
  }

  @Query(() => PaginatedClubResponse)
  public async searchClubs(
    @Arg('search', () => ClubSearchInput, { nullable: true }) search: ClubSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip = 0,
    @Arg('take', () => Int, { nullable: true }) take = 25,
    @Arg('order', () => [ClubSearchOrderInput], { nullable: true }) order: Array<ClubSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(Club, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = await ctx.em.findAndCount(Club, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    }));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [Club])
  async clubs(@Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.find(Club, getFindOptions(Club, info));
  }

  @Mutation(() => Club)
  async createClub(@Arg('input') input: ClubCreateInput, @Ctx() ctx: IRequestContext): Promise<Club> {
    const model = new Club();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Club)
  async updateClub(@Arg('input') input: ClubEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(Club, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  async deleteClubs(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(Club, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
