/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';

import { ClubNestedInput } from '../../club/inputs/ClubNestedInput'

// <keep-imports>
// </keep-imports>

@InputType()
export class HoleInOneNestedInput {
  @Field(() => EntityIdScalar, {"nullable":true})
  public id?: EntityId;

  @Field(() => Date, {"nullable":true})
  public date?: Date | null;

  @Field(() => String, {"nullable":true})
  public courseName?: string | null;

  @Field(() => Number, {"nullable":true})
  public holeNumber?: number | null;

  @Field(() => Number, {"nullable":true})
  public yardage?: number | null;

  @Field(() => ClubNestedInput, {"nullable":true})
  public club?: ClubNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
