/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';

import { SortOrderEnum } from '../../shared/SortOrderEnum'

// <keep-imports>
// </keep-imports>

@InputType()
export class HoleInOneSearchOrderInput {
  @Field(() => SortOrderEnum, {"nullable":true})
  public id?: SortOrderEnum;

  @Field(() => SortOrderEnum, {"nullable":true})
  public date?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public courseName?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public holeNumber?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public yardage?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public club?: SortOrderEnum | null;

  @Field(() => SortOrderEnum, {"nullable":true})
  public winner?: SortOrderEnum | null;

  // <keep-methods>
  // </keep-methods>
}
