/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Arg, Args, Mutation, Query, Info, ID, Ctx, Resolver, Root, FieldResolver, Int } from 'type-graphql';
import cleanDeep from 'clean-deep';

import { Round } from '../models/Round';
import { RoundCreateInput } from '../inputs/RoundCreateInput';
import { RoundEditInput } from '../inputs/RoundEditInput';
import { RoundSearchInput } from '../inputs/RoundSearchInput';
import { RoundSearchOrderInput } from '../inputs/RoundSearchOrderInput';
import { getFindOptions } from '../../shared/get-find-options';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { IRequestContext } from '../../shared/IRequestContext';
import * as auth from '../../authorization/auth-checkers';
import { PaginatedResponse } from '../../shared/PaginationResponse';
import { resolveGetters } from '../../shared/resolve-getters';

// <keep-imports>
// </keep-imports>

const PaginatedRoundResponse = PaginatedResponse(Round);

@Resolver(Round)
export class RoundCrudResolver {
  @Query(() => Round)
  async round(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.findOneOrFail(Round, id, getFindOptions(Round, info));
  }

  @Query(() => PaginatedRoundResponse)
  public async searchRounds(
    @Arg('search', () => RoundSearchInput, { nullable: true }) search: RoundSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip = 0,
    @Arg('take', () => Int, { nullable: true }) take = 25,
    @Arg('order', () => [RoundSearchOrderInput], { nullable: true }) order: Array<RoundSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(Round, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = await ctx.em.findAndCount(Round, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    }));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [Round])
  async rounds(@Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.find(Round, getFindOptions(Round, info));
  }

  @Mutation(() => Round)
  async createRound(@Arg('input') input: RoundCreateInput, @Ctx() ctx: IRequestContext): Promise<Round> {
    const model = new Round();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Round)
  async updateRound(@Arg('input') input: RoundEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(Round, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  async deleteRounds(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(Round, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
