/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, ObjectType } from 'type-graphql';
import { Column, JoinColumn, Entity, OneToOne, ManyToOne, OneToMany, PrimaryGeneratedColumn, CreateDateColumn, UpdateDateColumn } from 'typeorm';

import { User } from '../../user/models/User';
import { Week } from '../../week/models/Week';

import * as auth from '../../authorization/auth-checkers';
import { RoundCreateInput } from '../inputs/RoundCreateInput';
import { RoundEditInput } from '../inputs/RoundEditInput';
import { RoundNestedInput } from '../inputs/RoundNestedInput';
import { IRequestContext } from '../../shared/IRequestContext';
import { IAuthorizable } from '../../authorization/IAuthorizable';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { RoundAuth } from '../auth/RoundAuth';
import { getInputOperationType } from '../../shared/get-input-operation-type';
import { noChange } from '../../shared/no-change';
import { asPromise } from '../../shared/as-promise';

import { updateUserRelation } from './update-operations/round-update-operations';

// <keep-imports>
import { Unique } from 'typeorm';
// </keep-imports>

// <keep-decorators>
@Unique(['user', 'week'])
// </keep-decorators>
@Entity()
@ObjectType()
export class Round implements IAuthorizable {
  @Field(() => EntityIdScalar)
  @PrimaryGeneratedColumn()
  id: EntityId;

  public authorizationChecker = new RoundAuth(this);

  @Field(() => Number, )
  @Column({"type":"integer",
    // <custom-column-args>
    // </custom-column-args>
  })
  public score: number;

  @ManyToOne(() => User, (user) => user.rounds , {"nullable":false,"onDelete":"CASCADE"})
  @Field(() => User , {"nullable":false})
  public user: Promise<User>;

  @ManyToOne(() => Week, (week) => week.rounds , {"nullable":false,"onDelete":"CASCADE"})
  @Field(() => Week , {"nullable":false})
  public week: Promise<Week>;

  @CreateDateColumn()
  @Field()
  createdAt: Date;

  @UpdateDateColumn()
  @Field()
  updatedAt: Date;

  public async update(input: RoundCreateInput | RoundEditInput | RoundNestedInput, context: IRequestContext) {
    const { user, ...data } = input;
    if (noChange(input)) {
      return this;
    }
    if (getInputOperationType(this, input) === 'update') {
      await auth.assertCanUpdate(this, context);
    }
    Object.assign(this, data);

    if (getInputOperationType(this, input) === 'create') {
      this.week = asPromise(await this.week || await context.activeWeek)
    }
    await updateUserRelation(this, user, context);

    context.modelsToSave.push(this);

    // <keep-update-code>
    // </keep-update-code>
    await auth.assertCanPersist(this, context);

    return this;
  }

  // <keep-methods>
  // </keep-methods>
}
