/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Arg, Args, Mutation, Query, Info, ID, Ctx, Resolver, Root, FieldResolver, Int } from 'type-graphql';
import cleanDeep from 'clean-deep';

import { Year } from '../models/Year';
import { YearCreateInput } from '../inputs/YearCreateInput';
import { YearEditInput } from '../inputs/YearEditInput';
import { YearSearchInput } from '../inputs/YearSearchInput';
import { YearSearchOrderInput } from '../inputs/YearSearchOrderInput';
import { getFindOptions } from '../../shared/get-find-options';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { IRequestContext } from '../../shared/IRequestContext';
import * as auth from '../../authorization/auth-checkers';
import { PaginatedResponse } from '../../shared/PaginationResponse';
import { resolveGetters } from '../../shared/resolve-getters';

// <keep-imports>
// </keep-imports>

const PaginatedYearResponse = PaginatedResponse(Year);

@Resolver(Year)
export class YearCrudResolver {
  @Query(() => Year)
  async year(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.findOneOrFail(Year, id, getFindOptions(Year, info));
  }

  @Query(() => PaginatedYearResponse)
  public async searchYears(
    @Arg('search', () => YearSearchInput, { nullable: true }) search: YearSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip = 0,
    @Arg('take', () => Int, { nullable: true }) take = 25,
    @Arg('order', () => [YearSearchOrderInput], { nullable: true }) order: Array<YearSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(Year, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = await ctx.em.findAndCount(Year, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    }));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [Year])
  async years(@Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.find(Year, getFindOptions(Year, info));
  }

  @Mutation(() => Year)
  async createYear(@Arg('input') input: YearCreateInput, @Ctx() ctx: IRequestContext): Promise<Year> {
    const model = new Year();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Year)
  async updateYear(@Arg('input') input: YearEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(Year, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  async deleteYears(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(Year, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
