/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';

import { UserNestedInput } from '../../user/inputs/UserNestedInput'
import { HoleInOneNestedInput } from '../../hole-in-one/inputs/HoleInOneNestedInput'

// <keep-imports>
// </keep-imports>

@InputType()
export class HoleInOnePaymentObligationNestedInput {
  @Field(() => EntityIdScalar, {"nullable":true})
  public id?: EntityId;

  @Field(() => Boolean, {"nullable":true})
  public didPay?: boolean | null;

  @Field(() => Number, {"nullable":true})
  public amountToPay?: number | null;

  @Field(() => UserNestedInput, {"nullable":true})
  public userWithPaymentObligation?: UserNestedInput | null;

  @Field(() => HoleInOneNestedInput, {"nullable":true})
  public holeInOne?: HoleInOneNestedInput | null;

  // <keep-methods>
  // </keep-methods>
}
