/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';

import { ReferenceSearchInput } from '../../shared/ReferenceSearchInput'

// <keep-imports>
// </keep-imports>

@InputType()
export class HoleInOnePaymentObligationSearchInput {
  @Field(() => EntityIdScalar, {"nullable":true})
  public id?: EntityId;

  @Field(() => Boolean, {"nullable":true})
  public didPay?: boolean | null;

  @Field(() => Number, {"nullable":true})
  public amountToPay?: number | null;

  @Field(() => ReferenceSearchInput, {"nullable":true})
  public userWithPaymentObligation?: ReferenceSearchInput | null;

  @Field(() => ReferenceSearchInput, {"nullable":true})
  public holeInOne?: ReferenceSearchInput | null;

  // <keep-methods>
  // </keep-methods>
}
