/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';

import { UserNestedInput } from '../../user/inputs/UserNestedInput'
import { HoleInOneNestedInput } from '../../hole-in-one/inputs/HoleInOneNestedInput'

// <keep-imports>
// </keep-imports>

@InputType()
export class HoleInOnePaymentObligationCreateInput {
  @Field(() => Boolean, )
  public didPay: boolean;

  @Field(() => Number, )
  public amountToPay: number;

  @Field(() => UserNestedInput, )
  public userWithPaymentObligation: UserNestedInput;

  @Field(() => HoleInOneNestedInput, )
  public holeInOne: HoleInOneNestedInput;

  // <keep-methods>
  // </keep-methods>
}
