/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Arg, Args, Mutation, Query, Info, ID, Ctx, Resolver, Root, FieldResolver, Int } from 'type-graphql';
import cleanDeep from 'clean-deep';

import { HoleInOnePaymentObligation } from '../models/HoleInOnePaymentObligation';
import { HoleInOnePaymentObligationCreateInput } from '../inputs/HoleInOnePaymentObligationCreateInput';
import { HoleInOnePaymentObligationEditInput } from '../inputs/HoleInOnePaymentObligationEditInput';
import { HoleInOnePaymentObligationSearchInput } from '../inputs/HoleInOnePaymentObligationSearchInput';
import { HoleInOnePaymentObligationSearchOrderInput } from '../inputs/HoleInOnePaymentObligationSearchOrderInput';
import { getFindOptions } from '../../shared/get-find-options';
import { EntityId, EntityIdScalar } from '../../shared/EntityId';
import { IRequestContext } from '../../shared/IRequestContext';
import * as auth from '../../authorization/auth-checkers';
import { PaginatedResponse } from '../../shared/PaginationResponse';
import { resolveGetters } from '../../shared/resolve-getters';

// <keep-imports>
// </keep-imports>

const PaginatedHoleInOnePaymentObligationResponse = PaginatedResponse(HoleInOnePaymentObligation);

@Resolver(HoleInOnePaymentObligation)
export class HoleInOnePaymentObligationCrudResolver {
  @Query(() => HoleInOnePaymentObligation)
  async holeInOnePaymentObligation(@Arg('id', () => EntityIdScalar) id: number, @Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.findOneOrFail(HoleInOnePaymentObligation, id, getFindOptions(HoleInOnePaymentObligation, info));
  }

  @Query(() => PaginatedHoleInOnePaymentObligationResponse)
  public async searchHoleInOnePaymentObligations(
    @Arg('search', () => HoleInOnePaymentObligationSearchInput, { nullable: true }) search: HoleInOnePaymentObligationSearchInput | null = null,
    @Arg('skip', () => Int, { nullable: true }) skip = 0,
    @Arg('take', () => Int, { nullable: true }) take = 25,
    @Arg('order', () => [HoleInOnePaymentObligationSearchOrderInput], { nullable: true }) order: Array<HoleInOnePaymentObligationSearchOrderInput> = [],
    @Info() info,
    @Ctx() ctx: IRequestContext,
  ) {
    const defaultFindOptions = getFindOptions(HoleInOnePaymentObligation, info, { transformQueryPath: x => x.replace(/^items./, '') });

    const [items, total] = await ctx.em.findAndCount(HoleInOnePaymentObligation, cleanDeep({
      ...defaultFindOptions,
      skip,
      take,
      where: resolveGetters(search),
      order: Object.assign({}, ...order),
    }));

    return {
      items,
      total,
      hasMore: skip + take < total,
    };
  }

  @Query(() => [HoleInOnePaymentObligation])
  async holeInOnePaymentObligations(@Info() info, @Ctx() ctx: IRequestContext) {
    return await ctx.em.find(HoleInOnePaymentObligation, getFindOptions(HoleInOnePaymentObligation, info));
  }

  @Mutation(() => HoleInOnePaymentObligation)
  async createHoleInOnePaymentObligation(@Arg('input') input: HoleInOnePaymentObligationCreateInput, @Ctx() ctx: IRequestContext): Promise<HoleInOnePaymentObligation> {
    const model = new HoleInOnePaymentObligation();
    await model.update(input, ctx);

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => HoleInOnePaymentObligation)
  async updateHoleInOnePaymentObligation(@Arg('input') input: HoleInOnePaymentObligationEditInput, @Ctx() ctx: IRequestContext) {
    const model = await ctx.em.findOneOrFail(HoleInOnePaymentObligation, input.id);
    await model.update(input, ctx);

    // <keep-update-code>
    // </keep-update-code>

    await ctx.em.save(ctx.modelsToSave);

    return model;
  }

  @Mutation(() => Boolean)
  async deleteHoleInOnePaymentObligations(@Arg('ids', () => [ID]) ids: Array<EntityId>, @Ctx() ctx: IRequestContext): Promise<boolean> {
    const entities = await ctx.em.findByIds(HoleInOnePaymentObligation, ids);
    await auth.assertCanDelete(entities, ctx);
    await ctx.em.remove(entities);

    return true;
  }

  // <keep-methods>
  // </keep-methods>
}
