/* eslint-disable @typescript-eslint/no-unused-vars */
/*** AUTOGENERATED FILE: you can only modify parts of the file within <keep-*> tags ***/
import { Field, ID, InputType } from 'type-graphql';

import { EntityId, EntityIdScalar } from '../../shared/EntityId';

import { UserNestedInput } from '../../user/inputs/UserNestedInput'

// <keep-imports>
// </keep-imports>

@InputType()
export class RoundCreateInput {
  @Field(() => Number, )
  public score: number;

  @Field(() => UserNestedInput, )
  public user: UserNestedInput;

  // <keep-methods>
  @Field({ nullable: true, deprecationReason: 'No longer used' })
  public weekNumber?: number;

  @Field({ nullable: true, deprecationReason: 'No longer used' })
  public year?: number;
  // </keep-methods>
}
